### ISSUE TITLE
SCRAPPLE causes output log error

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-Output-Biomass#14]
When run with SCRAPPLE, Biomass output log file stops writing results after timestep 0

**Comment by rmscheller** [comment]
Alec, Did you try running without Scrapple?  I don't see a connection between the two extensions that would cause this error.

**Comment by akretchun** [comment]
I can't seem to reproduce this. I'm going to close it until I hit it again. Thanks!
