### ISSUE TITLE
crashed with DGS

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-Output-Biomass#19]
Was not updated with the new UniversalCohort library

![image](https://github.com/user-attachments/assets/824f89b9-1bc2-4616-acbe-6f55835b975c)

**Comment by rmscheller** [comment]
This is unrelated to the UCL.  Is has to do with the ISiteCohorts vs. SiteCohorts choice we made a while ago.  

I suspect DGS is still using ISiteCohorts.  All other extensions are now using SiteCohorts.

**Comment by mslucash** [comment]
You were right. Runs now! Thanks!  You can close this issue. However, note that I was still using ISiteCohorts in places because NECN still is. See CohortBiomass L489 as an example.

**Comment by rmscheller** [comment]
Good catch, although that variable is never used in that function.  It should be removed.
