### ISSUE TITLE
Simulation run not finding biomass output

### ISSUE THREAD

**Issue by gsotnik** [LANDIS-II-Foundation/Extension-Output-Biomass#4]
I'm running a scenario and an error message pops up notifying me that extension "Output Biomass" cannot be found. I redownloaded Extension Output Biomass 2.2, but this didn't help. I noticed that when the extension is being installed, it is directed to Program File/LANDIS-II/6.0. I followed the path and looked inside the 6.0 folder, but couldn't find it. I also can't find the new version with the other extensions in v6/bin/extensions.

**Comment by rmscheller** [comment]
Garry,

According to the User Guide, the keyword is "Biomass Output": https://drive.google.com/file/d/0B6eUM6Se6MFBRTZKRlY1bjJsYmc/view
