### ISSUE TITLE
error reading input value for extension

### ISSUE THREAD

**Issue by gsotnik** [LANDIS-II-Foundation/Extension-Output-Biomass#5]
![biomass output](https://cloud.githubusercontent.com/assets/13357134/26835192/90d76fb8-4a8c-11e7-8511-82bfd6833f37.JPG)

![biomasss output 2](https://cloud.githubusercontent.com/assets/13357134/26835273/cc61a1f2-4a8c-11e7-9a49-257955f8a8c5.JPG)

**Comment by bmarron18** [comment]
The document, "scenario_s2e1.txt" in the BiomassSuccession_s2e1 example in Support-Other repo correctly identifies and calls Extension-Output-Biomass,

  	"Output Biomass"		output_Biomass.txt

There is a typo in your version.

**Comment by rmscheller** [comment]
Bruce,
Perhaps what's confusing is that the extension name is "Biomass Output" (in PlugIn.cs) yet it is registered under "Output Biomass".   I don't have a preference but we should change them to be the same.
