### ISSUE TITLE
Metadata.InitializeMetadata is never called.

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Output-Biomass#8]
If it is not called, metadata not properly produced.

**Comment by bmarron18** [comment]
Running scenario_s2e1.txt (the QAQC example provided with Extension-Output-Biomass) calls "Biomass Succession"+ "Base Wind"+ "Biomass Harvest" + "Output Biomass" + "Output Biomass Reclass".  At completion of the run, the Metadata folder contains subfolders for Base Wind, Biomass Harvest, Biomass Succession, Climate-Library, Output Biomass, and Output Biomass Reclass. The subfolder for Output Biomass contains two files, "Output Biomass.xml" and "SummaryLog_Metadata.xml." Are these not the correct metadata files for Output Biomass? Is this scenario somehow not correctly calling and producing metadata?

**Comment by rmscheller** [comment]
Bruce, those are the correct files.  Perhaps I missed where it is being called.  I must have, will look again.

**Comment by rmscheller** [comment]
I see now where it's being called, needs some re-coding.  I will take care of it.
